import type { Metadata } from "next";
import "@/styles/globals.scss";
import { poppins } from "@/fonts";
import StateContextProvider from "@/context/StateCtx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StateContextProvider>
        <body className={poppins.className}>{children}</body>
      </StateContextProvider>
    </html>
  );
}
